name: Lint & Test

on:
  workflow_run:
    workflows: ["Push code to Repo"]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Run linter 👀
        run: yarn lint

      - name: Run tests 🧪
        run: yarn test
